//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrilledHoleSurvey
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DrilledHoleDbEntities : DbContext
    {
        public DrilledHoleDbEntities()
            : base("name=DrilledHoleDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_DrilledHole> Table_DrilledHole { get; set; }
        public virtual DbSet<Table_HoleDetail> Table_HoleDetail { get; set; }
        public virtual DbSet<View_HoleDetail> View_HoleDetail { get; set; }
    
        public virtual int Procedure_CheckDatabase()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Procedure_CheckDatabase");
        }
    }
}
