//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrilledHoleSurvey
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_HoleDepthInfo
    {
        public int Id { get; set; }
        public string HoleName { get; set; }
        public double Depth { get; set; }
        public double Dip { get; set; }
        public double Azimuth { get; set; }
    }
}
